[build]
  publish = "."

# El Puente MÃ¡gico
[[redirects]]
  from = "/api"
  to = "https://script.google.com/macros/s/AKfycbwMdaEIZi3EqnDbVoul-EjVfjvl4bCu3GOwteHAQtK3rFqdVVCuh0EVcaKVRqCJ2pezqQ/exec"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
